create extension if not exists pgcrypto;


-- =========================================================
-- LEADS
-- =========================================================

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),

  telegram_user_id text unique,
  first_name text,
  username text,

  source text,
  campaign text,
  ad_id text,

  fbclid text,
  meta_fbc text,
  meta_fbp text,

  user_agent text,
  landing_url text,

  stage text not null default 'NEW',
  score numeric not null default 0,

  pre_free_turns integer not null default 0,
  post_free_turns integer not null default 0,

  free_channel_invited boolean not null default false,
  free_channel_joined boolean not null default false,

  vip_offer_shown boolean not null default false,
  vip_offer_shown_at timestamptz,

  checkout_started boolean not null default false,
  last_checkout_plan text,

  paid boolean not null default false,
  paid_at timestamptz,

  paid_plan text,
  paid_amount numeric,
  paid_currency text,

  last_payment_status text,
  payment_refunded boolean not null default false,

  created_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- =========================================================
-- CONVERSATIONS
-- =========================================================

create table if not exists public.messages (
  id bigint generated by default as identity primary key,

  lead_id uuid not null
    references public.leads(id)
    on delete cascade,

  role text not null
    check (role in ('user', 'assistant')),

  content text not null,

  telegram_message_id bigint,

  created_at timestamptz not null default now()
);


-- =========================================================
-- AI CRITERIA
-- =========================================================

create table if not exists public.lead_criteria (
  lead_id uuid not null
    references public.leads(id)
    on delete cascade,

  criterion_key text not null,

  value numeric not null default 0
    check (value >= 0 and value <= 1),

  evidence text,

  updated_at timestamptz not null default now(),

  primary key (
    lead_id,
    criterion_key
  )
);


-- =========================================================
-- WHOP PAYMENTS
-- =========================================================

create table if not exists public.payments (
  id bigint generated by default as identity primary key,

  whop_payment_id text unique not null,

  lead_id uuid
    references public.leads(id)
    on delete set null,

  plan_key text,

  amount numeric,
  currency text,

  status text,

  raw_payload jsonb,

  created_at timestamptz not null default now()
);


-- =========================================================
-- WEBHOOK IDEMPOTENCY
-- =========================================================

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,

  provider text not null,

  event_id text not null,

  event_type text,

  payload jsonb,

  processed_at timestamptz not null default now(),

  unique (
    provider,
    event_id
  )
);


-- =========================================================
-- INDEXES
-- =========================================================

create index if not exists
idx_leads_telegram_user_id
on public.leads(telegram_user_id);

create index if not exists
idx_leads_score
on public.leads(score);

create index if not exists
idx_leads_stage
on public.leads(stage);

create index if not exists
idx_messages_lead_id
on public.messages(lead_id);

create index if not exists
idx_lead_criteria_lead_id
on public.lead_criteria(lead_id);

create index if not exists
idx_payments_lead_id
on public.payments(lead_id);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.leads
enable row level security;

alter table public.messages
enable row level security;

alter table public.lead_criteria
enable row level security;

alter table public.payments
enable row level security;

alter table public.webhook_events
enable row level security;


-- No public policies.
--
-- The backend uses the Supabase server secret key.
-- This prevents anonymous browser users from directly
-- reading your lead database.
